### ISSUE TITLE
What is the recommended adapter now that LanguageServerToJsonAdapter is deprecated?

### ISSUE THREAD

**Issue by natgabb** [TypeFox/ls-api#38]
The only example (in the blog post) uses the old approach. http://typefox.io/the-language-server-protocol-in-java

**Comment by akosyakov** [comment]
We should at least add javadoc to deprecated API.

**Comment by akosyakov** [comment]
@natgabb You should use LanguageServerEndpoint instead of LanguageServerToJsonAdapter. 

There are 2 classes now: LanguageClientEndpoint and LanguageServerEndpoint. LanguageClientEndpoint is used to connect to a language server from the tool (client) side. LanguageServerEndpoint is used to expose a language server to a client side. Both don't care about a protocol format anymore, whether it is json or not. This decision is hidden from them via MessageReader and MessageWriter.

**Comment by akosyakov** [comment]
@natgabb you can also have a look at [LanguageServerLauncher](https://github.com/TypeFox/ls-api/blob/00a052932452ada40009049fcf541bc41caba2ff/io.typefox.lsapi.services/src/main/java/io/typefox/lsapi/services/launch/LanguageServerLauncher.xtend#L50) to learn how to create and configure LanguageServerEndpoint.

**Comment by natgabb** [comment]
Thanks for the information!
