### ISSUE TITLE
ReferenceParamsBuilder creates instance of TextDocumentPositionParam instead of ReferenceParams

### ISSUE THREAD

**Issue by natgabb** [TypeFox/ls-api#39]
Ex:

```
new ReferenceParamsBuilder()
                .context(includeDeclaration)
                .textDocument(uri)
                .position(line, col)
                .uri(uri).build();
```

Creates an instance of `TextDocumentPositionParam` and needs to be casted if you want to use `ReferenceParams`.

**Comment by natgabb** [comment]
It's also the case for 

```
VersionedTextDocumentIdentifier textDocument = (VersionedTextDocumentIdentifier) 
                new VersionedTextDocumentIdentifierBuilder()
                                version(0)
                                .uri("")
                                .build();
```

Looks like it's probably true for all builders of extended interfaces.

**Comment by JanKoehnlein** [comment]
Cannot reproduce with the current head which did not receive any commits for three weeks now. How do you consume ls-api? Via Gradle?

**Comment by natgabb** [comment]
Yes I am using 0.3.0-SNAPSHOT via gradle. The bug only happens if you call a setter for one of the inherited attributes.

**Comment by JanKoehnlein** [comment]
Ah, I see. Seems like we're running into a similar problem [as JavaFX did](http://mail.openjdk.java.net/pipermail/openjfx-dev/2013-March/006725.html).

We could skip the IBuilder<T> interface and use builder classes only, then override each "setter" method in a subtype builder to return the more specialized builder type.

Or, we should give up the inheritance hierarchy of the builders. 

I'd go for the latter option as it is much less code and I am not sure whether builder hierarchies are a big benefit. Any objections?

**Comment by akosyakov** [comment]
- I don't see benefits from `IBuilder` interface, since you always program against a concrete builder, do you ever pass `IBuilder<?>` around?
- Agreed about overriding "setter", looks a bit clumsy. The question is whether there are clients who want to program against `TextDocumentIdentifierBuilder`. I guess so, for example to have a generic method to generate uris. I would prefer to keep a hierarchy for such case, but maybe have an interface hierarchy instead of a class hierarchy, e.g. `DidOpenTextDocumentParamsBuilderImpl` implements `DidOpenTextDocumentParamsBuilder` interface that extends `TextDocumentIdentifierBuilder` interface. Such interfaces are more meaningful compare to `IBuilder` and an implementation does not need to override setters.
- btw i don't like type guards in setters, if somebody wants to extend a protocol, it will be a showstopper.

**Comment by JanKoehnlein** [comment]
I've removed the type hierarchy of builders, which should resolve this issue. 

I agree we should remove the type guards in the builders, but it is currently far too complex. I've added a [separate issue](https://github.com/TypeFox/ls-api/issues/49) for that.

Removing the IBuilder interface now would also break API, so I left it and did not introduce another hierarchy for builders.
