### ISSUE TITLE
Builders should not rely on specific implementation for contained elements

### ISSUE THREAD

**Issue by JanKoehnlein** [TypeFox/ls-api#49]
Even though the builders do not expose the impl classes currently, they do instance-of checks on their arguments and throw exceptions. For users that want to extend the protocol that's a showstopper. We should not rely on arguments to be our specific generated impls.

**Comment by JanKoehnlein** [comment]
I have had a closer look at that and it currently has a lot of impact if we want to implement it without breaking API. 
- The impl classes would have to use upper bounded Lists/Maps instead, e.g.

```
CompletionListImpl.setItems(final List<? extends CompletionListItem> items)
```

instead of the current

```
CompletionListImpl.setItems(final List<CompletionListItemImpl> items)
```

This also requires to adapt the GSON part. 

We should postpone that to the moment when we switch to Eclipse and consolidate the API with minor breaks, e.g. remove these setters entirely as they break the immutability contract.

**Comment by spoenemann** [comment]
> For users that want to extend the protocol that's a showstopper.

Why? They can still extend the impls.

> This also requires to adapt the GSON part.

Yes, the main reason why the impls have references to the other impls instead of the interfaces is that this allows Gson to use its generic capabilities for parsing the structures. Changing all the references to interfaces would require huge adaptations to Gson. I tried that in the beginning, but it felt like a dead end.

> remove these setters entirely as they break the immutability contract

Immutability would mean that the information attached to an impl instance has to be gathered all in the same place. I went for the mutable approach since that allows the instances to be constructed step by step.

**Comment by JanKoehnlein** [comment]
WRT immutability and step by step construction: Why do we have a builder API then?

**Comment by spoenemann** [comment]
Because it was requested: #15

**Comment by akosyakov** [comment]
Could we consider to use classes instead of interfaces for immutable data types, e.g. `Position`, `Range`, etc., and keep interfaces only for services, e.g. `LanguageServer`, `TextDocumentService`, etc.?

**Comment by spoenemann** [comment]
If we decide to make the implementations immutable, we can safely drop the interfaces, since originally those were just meant to hide the setters.

**Comment by svenefftinge** [comment]
I'd like to go without interfaces, immutable objects and builders.

**Comment by bruno-medeiros** [comment]
+1 for immutable objects.

**Comment by spoenemann** [comment]
@bruno-medeiros: I think Sven's proposal was to _not_ support immutable objects, nor builders. See #50.

**Comment by svenefftinge** [comment]
Yes, I would like to make it as simple as possible. :
"""
In order to have zero Xtend usage we could go even a step further and use Java structs, i.e. without getters and setters. They don't make much sense here anyway, as we want to reflect the underlying Json structures as much as possible. So I don't see why anyone would implement custom getters and setters on those classes.
"""

**Comment by bruno-medeiros** [comment]
Oh right, I misread.

Immutable objects are slightly more complex to write but add some safety. Not that it's a big issue either way, just a nice to have thing. 

Also you can have immutable objects in Java without getters/setters, using the `final` keyword... although you also need immutable interfaces for Java collections, which Java unfortunately doesn't provide in the standard lib (only immutable wrappers that check at runtime).

**Comment by spoenemann** [comment]
A nice property of the public-fields approach proposed by Sven is that the structures are much closer to the original specification, which is in TypeScript and thus describes plain JS objects. I believe this will make it easier to maintain the structures and stay up-to-date with the specification. We will no longer need to generate the code, so the source will be easier to understand for people without Xtend xperience.

I'm closing the issue since builders are no longer generated.
