### ISSUE TITLE
Consider re-introducing an inheritance hierarchy of builders

### ISSUE THREAD

**Issue by JanKoehnlein** [TypeFox/ls-api#50]
See comments in issue #39.

**Comment by svenefftinge** [comment]
In the lsp4j branch I removed a lot of the stuff that is being generated, which makes the whole thing much simpler. So no interfaces and no builders, just JavaBeans.

In order to have zero Xtend usage we could go even a step further and use Java structs, i.e. without getters and setters. They don't make much sense here anyway, as we want to reflect the underlying Json structures as much as possible. So I don't see why anyone would implement custom getters and setters on those classes.

**Comment by svenefftinge** [comment]
we decided to not have builders at all
